language: node_js
node_js:
- lts/*
cache:
  yarn: true
  directories:
  - node_modules
install: yarn
script:
- yarn install && yarn export
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: vO6gFRXScEPlo/2vjsVoiKBw0eeJnADST1Dm16Iiodr3VzkSRf+th3urfN0zoMdcUNnmze70mI45YLN8FcG/nZC3QD3+KUgafrNDMeHdajla94as5fT84r/XXkAO/y3CHT861Mas67uJHP56q4RRgNSsYsCxgx/E/gu/bZ833gyjNyUx3NXhIWCIph+5hj18uhCrpiPLq8PxQstFoxsmv3hItcKiN1rFpHhZPw25Q91hXn5wkf3qrZ9NDikQPGwnBj9DX5/LSYkSBHFltusiO0mK6bn0jgka5hd7FmDIPPk8HpEocMgZbcU6u7NuXin/eWKICCiuIKdSUanWNlQyF4sPJ0bRTVPlfnHhM+z2MsumVwR4wggFDbcSkA2WEF2H2mtfbICrNUKU1H/kZpetXp7tetPwaxjMXwc9lefbw7rFQ9s4QB/KgpjDoG7uD787OJ5JTn6IjcEImOMdlFg6GZRwg/5KZQP2MMY9+GJLpmO5gR/NqD2iPPsiRstccgirNfdik7UukvQIhKTu3Mq4rYkd4HQw5gViXWe2WZBT4dcQl2Sz4pgzA/1nof+MPypxpnfIxMSnbIXDYnjixUrQ4HLdIt9/64I/q2gq589QVL9lTXL2O4gUyR8YAeJNQFv7xPTGg0FdWdhY6OYgorkkwQbrJMvYzNr4J9KK3trFYWw=
  on:
    branch: master