language: node_js
node_js:
- lts/*
cache:
  yarn: true
  directories:
  - node_modules
install: yarn
script:
- yarn install && yarn export
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: CI5GMeP82Qg1twJp+pwxgrblN/wRpBL+mYUj82wNaPN7lkXQdE/WkkR12h8KsONuMLxYOkB6YDhs22qxeRU7ZM5P9nRZYbirIGu8XpBI0fANTlFP8TERf0ly1GfknIYXeb6JBs5FuPZC3lFzsuwVCKYxmeVSK9GVGmgx2pE9jZ1S75blrT9owaUSKIbuGZ3CBCNP7053U5AajBGJSUCdRnV5w4ZPrf7hnHBJT9trPKSn0DRPdGWyZzJjv/mMhf5+aBFS9wQoB42aWWo/kLeUnQrFd2kp7B0jsZKKoniB0Cj5m7Newcq+fCHce8flVyCXGSWwQto1bvjdAEA2pTQZ1PQaf1pD4cfXlLWXxNYe0IzF4PtacpCr7rrUo0FmH1y3wMZl+yq/m5FlnpPFVmPE2A0Oap5a1zov4PKt1GYP5Kp3Xw+JGYDZgu5eKxM9PZ3N2u5qNHQLjyQro902g+vMiCRSPbtjd+bCn5SVf/B0yliLqZPGzkOfzBPitKq6Igyae9iVYiDwhwuCXwb2bQw5clF3aEbL1mQ1iECGbJ8zx4gsvjahhM2cBqyaEEBAE7h8OmEIT+AcHUSz9nMG4VCYjWN9AJF8envay7ebasyRdljL9hUYRcLiAdyj/V9MVGMOO+mQhwf3I8UfaJAwSB1dn2pqGbb2om3UwqXJEzGAlnY=
  on:
    branch: master
env:
  global:
    secure: CI5GMeP82Qg1twJp+pwxgrblN/wRpBL+mYUj82wNaPN7lkXQdE/WkkR12h8KsONuMLxYOkB6YDhs22qxeRU7ZM5P9nRZYbirIGu8XpBI0fANTlFP8TERf0ly1GfknIYXeb6JBs5FuPZC3lFzsuwVCKYxmeVSK9GVGmgx2pE9jZ1S75blrT9owaUSKIbuGZ3CBCNP7053U5AajBGJSUCdRnV5w4ZPrf7hnHBJT9trPKSn0DRPdGWyZzJjv/mMhf5+aBFS9wQoB42aWWo/kLeUnQrFd2kp7B0jsZKKoniB0Cj5m7Newcq+fCHce8flVyCXGSWwQto1bvjdAEA2pTQZ1PQaf1pD4cfXlLWXxNYe0IzF4PtacpCr7rrUo0FmH1y3wMZl+yq/m5FlnpPFVmPE2A0Oap5a1zov4PKt1GYP5Kp3Xw+JGYDZgu5eKxM9PZ3N2u5qNHQLjyQro902g+vMiCRSPbtjd+bCn5SVf/B0yliLqZPGzkOfzBPitKq6Igyae9iVYiDwhwuCXwb2bQw5clF3aEbL1mQ1iECGbJ8zx4gsvjahhM2cBqyaEEBAE7h8OmEIT+AcHUSz9nMG4VCYjWN9AJF8envay7ebasyRdljL9hUYRcLiAdyj/V9MVGMOO+mQhwf3I8UfaJAwSB1dn2pqGbb2om3UwqXJEzGAlnY=
