language: node_js
node_js:
- 8
cache:
  yarn: true
  directories:
  - node_modules
install: yarn
script:
- yarn install && yarn export
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: IxiNkZ25G4zKHTqfPmPMywpSnRbXdhNsMzyS0SO34uviuiuivR4rB+wQD383LwtQhRn821EVaKiX4R+LiV5DhUT9U2tkGElDb+Uoviqn0pveJoqvvGWcEnwnGi9CCwl+3MB1HEYchZjfD0SufyUuosuzRlKeh9Y8Dg04umq8CzGk1RVGEC86+2qVwAuS+5G9NDNSxAj1klVWcOJvWwzUigH9LbyJ3gAPxTk4BnzOxCA6MWxEbuqW1kabEmHiykM1ZZxLhdHG8YjiqlrhL5m2SDa35l79+tM0MQYnAiF0yWq2FB6TCHQf/QGKIZ6QLAZ0mbJMyuzyfrGzIlMIzmMifD3tK6lAyDPCi32Rl+Ie/GifcThchRYcDxSukg6biPQHyZBEutAdFTx5tjMAg/7mRbdPv6iuOHvIQehRRIdtUvDltKhYNbOLA2hA6aayfybmbi4iGb+9Nt+E9pVEkoXbnSF5HgeMAa25AIC2R//Gp5Is7iaBxpl7yd4yQeiAUDurrYjHC4hrFNlxNmAEwltm/4musXr6Mc7tMseQCV24zgeS2dy0k3tVYz0Ns8+zP4031mntpSxwNRPWwD8NCiWnHrYmZ58x3K9sGO3eFQd4x4OgV2lDXQw6S04WkJvNRSBZq3bnngXq9iLjUp2PD7PIMPCnCZYR4QWgwCEtz9SHSqw=
  on:
    branch: master
